#!/usr/bin/env python
 
import httplib
import json
import os
import sys
import urllib
 
def translate(part):
    conn = httplib.HTTPConnection("suggest-slovari.yandex.ru")
    params = urllib.urlencode({"v": "2", "lang": "", "part": part})

    conn.request("GET", "/suggest-lingvo?" + params)
    resp = conn.getresponse()

    return json.loads(resp.read())[1]

def usage(prog):
    print "%s <term>\n" % prog

if __name__ == "__main__":
    try:
        term = sys.argv[1]
    except IndexError:
        usage(sys.argv[0])
        sys.exit(1)

    for translation in translate(term):
        print translation
