#!/usr/bin/env python

import argparse
import httplib
import json
import locale
import os
import sys
import urllib

from yasl.cache import Cache
from yasl.utils import htmlunescape

system_encoding = locale.getpreferredencoding()


def translate(part):
    conn = httplib.HTTPConnection("suggest-slovari.yandex.ru")
    params = urllib.urlencode({"v": "2", "lang": "",
        "part": part.encode("utf-8")})

    conn.request("GET", "/suggest-lingvo?" + params)
    resp = conn.getresponse()

    return htmlunescape('\n'.join([translation
        for translation in json.loads(resp.read())[1]]))


def get_argparser():
    parser = argparse.ArgumentParser(
            description='CLI client for slovari.yandex.ru',
            epilog='send bug reports to: bogorodskiy@gmail.com')
    parser.add_argument('-n', dest='use_cache',
            default=True, action='store_false',
            help="do not use cache")
    parser.add_argument('term', nargs='+',
            help='a term to translate')

    return parser


if __name__ == "__main__":
    args = get_argparser().parse_args()

    term = " ".join(args.term).decode(system_encoding)

    if args.use_cache:
        cache = Cache()
        output = cache.find(term)

        if not output:
            output = translate(term)
            if 0 == len(output):
                print "No translations found."
                sys.exit(1)
            cache.add(term, output)

        cache.update(term)
    else:
        output = translate(term)

    print output.encode(system_encoding)
